"""Initial Create

Revision ID: 112c2033c890
Revises:
Create Date: 2026-01-09 13:44:25.042352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "112c2033c890"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(length=255), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("orderid", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
    )
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sku", name=op.f("pk_products")),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("sku", sa.String(length=255), nullable=True),
        sa.Column("_purchased_quantity", sa.Integer(), nullable=False),
        sa.Column("eta", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sku"], ["products.sku"], name=op.f("fk_batches_sku_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("orderline_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_allocations_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["orderline_id"],
            ["order_lines.id"],
            name=op.f("fk_allocations_orderline_id_order_lines"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allocations")
    op.drop_table("batches")
    op.drop_table("products")
    op.drop_table("order_lines")
    # ### end Alembic commands ###
